### PR TITLE
Support for IDEA version 2022.1

### PR DESCRIPTION
**Pull request by RinOrz**
image

### CODE REVIEW

**Comment by ragurney** [comment]
Thanks for the PR! I would actually prefer to keep the upper-bound in case there are breaking future SDK changes. Which version are you trying to use this plugin with? Can you update the diff to that version, then we can run the validation workflow via IntelliJ platform to ensure this plugin will continue to work as expected?

**Comment by RinOrz** [comment]
Okay, it's version 2022.1

**Review by paddy-flynn — APPROVED** [review]

**Comment by ragurney** [comment]
Nice! Running checks now. If they pass I'll release by EOD.

**Comment by ragurney** [comment]
LGTM

**Review by ragurney — APPROVED** [review]

**Pull request merged**
